version: '3.11'
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  db:
    container_name: "db"
    image: postgres:15.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - DB_HOST=${DB_HOST}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    container_name: "redis"
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data: