version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:15.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - DB_HOST=${DB_HOST}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: