"""change reaction model

Revision ID: 3308dfb712d6
Revises: cde94bd9ef3d
Create Date: 2023-07-06 16:49:56.653981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3308dfb712d6'
down_revision = 'cde94bd9ef3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
